### ISSUE TITLE
Stop working on the cohesion-alignment-separation-model

### ISSUE THREAD

**Issue by SteffenRandrup** [mismosmi/idea2birds#6]
While it's nice to see you contributing, you should consider working on the project we are supposed to be working on.
Part of our project is to replicate an already published paper and verify its results. Only then should we add something, not write a completely different model.
The tutorial works well as inspiration, but it is not within the scope of the task we were given.

In the viksec-model wrapping works, cone-like vision is as simple as checking the size of the inner product between relative positions and velocity and should reduce to the simple model just from setting the angle of the cone to 2\pi.

**Comment by SteffenRandrup** [comment]
Namiko said today, that if we want to, we may use the cohesion-alignment-separation-model for comparison with the vicsek-model. But we should be aware, that we only have 4 pages for the final report, and we might not be able to fit in desription and results from both.

**Comment by mismosmi** [comment]
The viksec model is the alignment-cohesion-separation model just without cohesion and separation and these can be disabled with command line parameters. It is faster and more flexibel and has no wrapping problems as well.

**Comment by mismosmi** [comment]
But if you prefer to use the pure viksec version i don't mind, i don't care i had to figure it out :). I guess the most important thing is that we figure out a way to evaluate it and to put our results into numbers.

**Comment by SteffenRandrup** [comment]
I think, it would be really cool, if we could add cohesion and separation on top, once we have verified, we get the same results as the viksec model. I just didn't want to waste effort on code, that we won't use. Also I don't think the alignment part is implemented the same way, as the viksec paper describes it, which is also a requirement for verifying their results, but feel free to correct me on that one.

As far as quantifying the results, Namiko said that we should try to reproduce the plots from the paper and check, that ours look similar. We don't have to do all of them just pick 1 or 2. Then we should do a similar plot for varying angles in the cone-vision addition. The plots in the paper are based on this v_a property. This is currently being printed in the viksec branch. That is obviously not a good solution, but the calculation of the property is implemented.
I suggest, we run some number of iterations and then save the value of v_a (or maybe an average over a few more iterations) and then reset the system and change one of the base parameters and go again.  This should provide us with plottable results without major modifications.

**Comment by mismosmi** [comment]
I'll have a look into it. Maybe we could meet again some time tomorrow if you and @andreitimus95 are free, discuss this in person and, this time, actually split some work since implementation is done so far in any case.

**Comment by mismosmi** [comment]
checked it out, compared the versions, implemented a setting where both versions can be run without any randomness and exactly 3 birds in the same starting positions. If you want to compare it too you can do so:
```
git pull --all
git show master:src/birds.py > birds_master.py
```
and then run the master-version with the following parameters:
```
python3 birds_master.py --cohesion 0 --separation 0 --height 360 --alignment_radius 10 --min_velocity 1 -r 0 -n 3 --angle 0
```
and the vicsek-version with
```
python3 birds.py -n 3 --mu 0
```
(I added -n option for easier switching between low/high numbers of birds and --mu 0 turns off randomness)

If you also outcomment the cone-limiting part they should be fully comparable and you can try out different initial settings for the "3 bird mode".

you can also see that the vicsek-version actually has a wrapping issue as the birds should fly straight in one direction as long as all angles are either 0 or 180 degrees. I could not find the bug yet and do not yet understand how your angle-limiting works so don't know how to set my parameter so that they are comparable. seems like something to have another go at tomorrow during daytime.

Logic-wise I might be mistaken but I think the alignment is the same: the mean direction of all birds in the set radius.

**Comment by mismosmi** [comment]
tomorrow I will implement the rest to fit the vicsek paper as now there's really not much left to do and output the v_a as well. I guess if we have both versions output roughly the same thing we can at least be pretty sure we're doing it right.
maybe there's also some numpy-way to store the data that makes it easier to plot afterwards.

**Comment by andreitimus95** [comment]
Hi,

Sorry I couldn't come friday, is there anything I can help with regarding
the project?

**Comment by mismosmi** [comment]
@SteffenRandrup check out the master branch.
